"""Add order column to Task model

Revision ID: 46377efe98cc
Revises: 
Create Date: 2025-01-28 11:41:04.834872

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '46377efe98cc'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.add_column(sa.Column('order', sa.Integer(), nullable=True))
        batch_op.alter_column('points',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('task_type',
               existing_type=sa.VARCHAR(length=10),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.alter_column('task_type',
               existing_type=sa.VARCHAR(length=10),
               nullable=True)
        batch_op.alter_column('points',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.drop_column('order')

    # ### end Alembic commands ###
